export const environment = {
  production: true,
  apiUrl: 'https://api.yourdomain.com/api',
  signalRHub: 'https://api.yourdomain.com/hubs/imports',
  enableSignalR: true,
  enableMockServer: false,
  enablePWA: true,
  cacheTTL: 300000,
  defaultLanguage: 'en',
  supportedLanguages: ['en', 'hi'],
  maxUploadSize: 50 * 1024 * 1024,
  chunkSize: 1024 * 1024,
  barcodeScannerTimeout: 5000,
  voiceCommandEnabled: true,
  autoRefreshInterval: 30000,
};
